# Config file for SimpleFTPSync

sync-interval: 300  # Synchronizations interval in seconds
local-path: "path/to/local/folder" # Path to local folder
sync-type: "FTP" # Synchronization type (FTP SFTP or FTPS)

# FTP server configuration
ftp:
  server: "ftp.example.com"
  port: 21
  username: "your-ftp-username"
  password: "your-ftp-password"
  remote-path: "/path/on/ftp/server"

# SFTP server configuration
sftp:
  server: "sftp.example.com"
  port: 22
  username: "your-sftp-username"
  password: "your-sftp-password"
  remote-path: "/path/on/sftp/server"
  StrictHostKeyChecking: "yes" # Set to "yes" or "no" to enable or disable strict host key checking (not recommended)

# FTPS server configuration
ftps:
  server: "ftps.example.com"
  port: 21
  username: "your-ftps-username"
  password: "your-ftps-password"
  remote-path: "/path/on/ftps/server"

# List of folders to synchronize
sync-folders:
  - local-path: "plugins/YourPluginName/folder1"
    remote-path: "/remote/folder1"
  - local-path: "world"
    remote-path: "/remote/folder2"
    # Add more folders as needed